AWSTemplateFormatVersion: '2010-09-09'

Description: >
  Constructs a managed IAM policy to deploy a serverless project.

  This template assumes the stack is being deployed in the current region and account.
  You can then attach this policy to other IAM objects, such as users or roles.

  Based on the work done in: https://github.com/serverless/serverless/issues/1439

Parameters:

  Stage:
    Description: >-
      The stage for this project.
    Type: String

Resources:

  ClientUser:
    Type: AWS::IAM::User
    Properties:
      UserName: "WebRtcClient"
      Policies: []  # Prefer managing policies separately.


  ClientPolicy:
    # Cumulative inline policy size cannot exceed 2,048 characters for IAM Users.
    # Cloudformation will hang waiting for an update exceeding this amount to complete.
    # https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_iam-limits.html
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Users:
        - !Ref ClientUser
      ManagedPolicyName: !Sub 'webrtc-${Stage}-ClientPolicy'
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: WebRtcAction
            Effect: Allow
            Action:
              - kinesisvideo:*
            Resource: "*"